version: '3'

services:
  nifi:
    cap_add:
      - NET_ADMIN # low port bindings
    image: apache/nifi
    container_name: nifi
    ports:
      - "514:514/tcp" # Syslog
      - "514:514/udp" # Syslog
      - "2055:2055/udp" # NetFlow
    volumes:
      - /opt/nifi/drivers:/opt/drivers
      - nifi-conf:/opt/nifi/nifi-current/conf
    restart: unless-stopped

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - /opt/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - /opt/nginx/keys:/keys
    ports:
      - "8443:8443/tcp" # HTTPS interface
    restart: unless-stopped

volumes:
  nifi-conf:
